name: Flutter CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    name: Check the source code
    steps:
      - uses: actions/checkout@v4
      - name: create firebase_options.dart
        run: |
          echo "$FIREBASE_OPTIONS_BASE64" | base64 -d > lib/firebase_options.dart
        env:
          FIREBASE_OPTIONS_BASE64: ${{ secrets.FIREBASE_OPTIONS_BASE64 }}

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set JAVA_HOME for Gradle
        run: echo "org.gradle.java.home=$JAVA_HOME" >> android/gradle.properties

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
          cache: true

      - name: Clean build artifacts
        run: flutter clean

      - name: Install packages
        run: flutter pub get

      - name: Check code formatting
        run: dart format --set-exit-if-changed .

      - name: Fluitter test
        run: flutter test --coverage
        env:
          FLUTTER_TEST_TIMEOUT: 120